service: ddns-route53-dmwl

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: aclTable
            sources: [./seeds/acl.json]
          - table: clientsTable
            sources: [./seeds/clients.json]
          - table: domainsTable
            sources: [./seeds/domains.json]


provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  environment:
    DYNAMODB_TABLE_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - route53:ChangeResourceRecordSets
      Resource: "arn:aws:route53:::hostedzone/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_PREFIX}-*"


functions:
  update:
    handler: handler.update
    events:
      - http:
          path: ddns/update
          method: get

resources:
  Resources:
    aclTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: client_id
            AttributeType: S
          - AttributeName: fqdn
            AttributeType: S
          - AttributeName: hosted_zone_id
            AttributeType: S
        KeySchema:
          - AttributeName: client_id
            KeyType: HASH
          - AttributeName: fqdn
            KeyType: RANGE
          - AttributeName: hosted_zone_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-acl
    domainsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hosted_zone_id
            AttributeType: S
          - AttributeName: domain
            AttributeType: S
        KeySchema:
          - AttributeName: hosted_zone_id
            KeyType: HASH
          - AttributeName: domain
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-domains
    clientsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: client_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: client_id
            KeyType: HASH
          - AttributeName: email
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PREFIX}-clients
